# Generated by Django 4.1.4 on 2022-12-09 15:09

import CryptoTradingApp.core.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
