# Generated by Django 4.1.4 on 2022-12-09 15:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0002_create_crypto_currency_and_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "traded_currency_one",
                    models.CharField(
                        choices=[
                            ("crypto_Bitcoin", "Bitcoin"),
                            ("crypto_Ethereum", "Ethereum"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "traded_currency_two",
                    models.CharField(
                        choices=[
                            ("crypto_Bitcoin", "Bitcoin"),
                            ("crypto_Ethereum", "Ethereum"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "traded_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-07)]
                    ),
                ),
                ("date_of_trade", models.DateField(auto_now_add=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trader_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="crypto.cryptowallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_purchase", models.DateField(auto_now_add=True)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-07)]
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("crypto_wallet", "Crypto Wallet"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("crypto_Bitcoin", "Bitcoin"),
                            ("crypto_Ethereum", "Ethereum"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
