# Generated by Django 4.1.4 on 2022-12-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0003_balanceincrease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balanceincrease",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mobile_payment", "Mobile payment"),
                    ("bank_transfer", "Electronic bank transfer"),
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("paypal", "PayPal"),
                ],
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="balanceincrease",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mobile_payment", "Mobile payment"),
                    ("bank_transfer", "Electronic bank transfer"),
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("paypal", "PayPal"),
                ],
                max_length=14,
            ),
        ),
    ]
