# Generated by Django 4.1.4 on 2022-12-09 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_balanceincrease_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balanceincrease",
            name="amount",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(10)]
            ),
        ),
    ]
