# Generated by Django 4.1.4 on 2022-12-11 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0010_cryptosale_buyer_alter_cryptosale_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptosale",
            name="buyer",
            field=models.ForeignKey(
                choices=[
                    (2, "Misho Simeonov"),
                    (1, "Mihail Terziev"),
                    (3, "Misho Georgiev"),
                ],
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
