# Generated by Django 4.1.4 on 2022-12-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0011_alter_cryptosale_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptopurchase",
            name="currency",
            field=models.CharField(
                choices=[
                    ("Bitcoin", "Bitcoin"),
                    ("Ethereum", "Ethereum"),
                    ("Dogecoin", "Dogecoin"),
                    ("TomatoCoin", "TomatoCoin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptosale",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cryptosale",
            name="currency",
            field=models.CharField(
                choices=[
                    ("Bitcoin", "Bitcoin"),
                    ("Ethereum", "Ethereum"),
                    ("Dogecoin", "Dogecoin"),
                    ("TomatoCoin", "TomatoCoin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptotrade",
            name="traded_currency_one",
            field=models.CharField(
                choices=[
                    ("Bitcoin", "Bitcoin"),
                    ("Ethereum", "Ethereum"),
                    ("Dogecoin", "Dogecoin"),
                    ("TomatoCoin", "TomatoCoin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptotrade",
            name="traded_currency_two",
            field=models.CharField(
                choices=[
                    ("Bitcoin", "Bitcoin"),
                    ("Ethereum", "Ethereum"),
                    ("Dogecoin", "Dogecoin"),
                    ("TomatoCoin", "TomatoCoin"),
                ],
                max_length=20,
            ),
        ),
    ]
