# Generated by Django 4.1.4 on 2022-12-09 15:09

import CryptoTradingApp.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
