# Generated by Django 4.1.4 on 2022-12-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_balanceincrease_date_of_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balanceincrease",
            old_name="payment_method",
            new_name="transaction_method",
        ),
    ]
