# Generated by Django 4.1.4 on 2022-12-11 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0002_create_crypto_currency_and_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0008_trade_converted_from_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_purchase", models.DateField(auto_now_add=True)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-07)]
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wallet_balance", "Crypto wallet balance"),
                            ("mobile_payment", "Mobile payment"),
                            ("bank_transfer", "Electronic bank transfer"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("Ethereum", "Ethereum"),
                            ("Dogecoin", "Dogecoin"),
                            ("Bitcoin", "Bitcoin"),
                            ("TomatoCoin", "TomatoCoin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptoSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_sale", models.DateField(auto_now_add=True)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-07)]
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("Ethereum", "Ethereum"),
                            ("Dogecoin", "Dogecoin"),
                            ("Bitcoin", "Bitcoin"),
                            ("TomatoCoin", "TomatoCoin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptoTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "traded_currency_one",
                    models.CharField(
                        choices=[
                            ("Ethereum", "Ethereum"),
                            ("Dogecoin", "Dogecoin"),
                            ("Bitcoin", "Bitcoin"),
                            ("TomatoCoin", "TomatoCoin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "traded_currency_two",
                    models.CharField(
                        choices=[
                            ("Ethereum", "Ethereum"),
                            ("Dogecoin", "Dogecoin"),
                            ("Bitcoin", "Bitcoin"),
                            ("TomatoCoin", "TomatoCoin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "traded_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-07)]
                    ),
                ),
                ("converted_from_quantity", models.FloatField()),
                (
                    "converted_to_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-07)]
                    ),
                ),
                ("date_of_trade", models.DateField(auto_now_add=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trader_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="crypto.cryptowallet",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="trade",
            name="trader",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="trader_wallet",
        ),
        migrations.AlterField(
            model_name="balanceincrease",
            name="transaction_method",
            field=models.CharField(
                choices=[
                    ("mobile_payment", "Mobile payment"),
                    ("bank_transfer", "Electronic bank transfer"),
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("paypal", "PayPal"),
                ],
                max_length=14,
            ),
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="Trade",
        ),
    ]
