# Generated by Django 4.1.4 on 2022-12-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "common",
            "0012_alter_cryptopurchase_currency_alter_cryptosale_buyer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptopurchase",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TomatoCoin", "TomatoCoin"),
                    ("Bitcoin", "Bitcoin"),
                    ("Dogecoin", "Dogecoin"),
                    ("Ethereum", "Ethereum"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptosale",
            name="currency",
            field=models.CharField(
                choices=[
                    ("TomatoCoin", "TomatoCoin"),
                    ("Bitcoin", "Bitcoin"),
                    ("Dogecoin", "Dogecoin"),
                    ("Ethereum", "Ethereum"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptotrade",
            name="traded_currency_one",
            field=models.CharField(
                choices=[
                    ("TomatoCoin", "TomatoCoin"),
                    ("Bitcoin", "Bitcoin"),
                    ("Dogecoin", "Dogecoin"),
                    ("Ethereum", "Ethereum"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cryptotrade",
            name="traded_currency_two",
            field=models.CharField(
                choices=[
                    ("TomatoCoin", "TomatoCoin"),
                    ("Bitcoin", "Bitcoin"),
                    ("Dogecoin", "Dogecoin"),
                    ("Ethereum", "Ethereum"),
                ],
                max_length=20,
            ),
        ),
    ]
